version: '3'

services:
  db:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  web:
    build: .
    command: tail -F anything
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db